obj-m			 += cfg80211.o
obj-m			 += lib80211.o
obj-m			 += lib80211_crypt_wep.o
obj-m			 += lib80211_crypt_ccmp.o
obj-m			 += lib80211_crypt_tkip.o

obj-y			 += wext-core.o
obj-y			 += wext-proc.o
obj-y			 += wext-spy.o
obj-y			 += wext-priv.o

cfg80211-y 		+= core.o sysfs.o radiotap.o util.o reg.o scan.o nl80211.o
cfg80211-y 		+= mlme.o ibss.o sme.o chan.o ethtool.o mesh.o
cfg80211-y		+= wext-compat.o wext-sme.o
