#!/bin/bash

ifconfig eth0 down
ifconfig eth0 up
ifconfig eth0 192.168.1.98/24
route add default gw 192.168.10.1
echo nameserver 61.139.2.69 >> /etc/resolv.conf
echo nameserver 8.8.8.8 >> /etc/resolv.conf
