obj-m		+= mac80211.o

# mac80211 objects
mac80211-y := \
	main.o status.o \
	sta_info.o \
	wep.o \
	wpa.o \
	scan.o offchannel.o \
	ht.o agg-tx.o agg-rx.o \
	ibss.o \
	mlme.o work.o \
	iface.o \
	rate.o \
	michael.o \
	tkip.o \
	aes_ccm.o \
	aes_cmac.o \
	cfg.o \
	rx.o \
	spectmgmt.o \
	tx.o \
	key.o \
	util.o \
	wme.o \
	event.o \
	chan.o

mac80211-y		+= led.o

mac80211-y		 += \
	mesh.o \
	mesh_pathtbl.o \
	mesh_plink.o \
	mesh_hwmp.o

mac80211-y += pm.o

# objects for PID algorithm
rc80211_pid-y := rc80211_pid_algo.o

rc80211_minstrel-y := rc80211_minstrel.o

rc80211_minstrel_ht-y := rc80211_minstrel_ht.o

mac80211-y += $(rc80211_minstrel-y)
mac80211-y += $(rc80211_minstrel_ht-y)
